networks:
  my-network:
    name: rs-nodejs-network

services:
  db:
    build:
      context: ./dockerfiles/db
      dockerfile: Dockerfile
    container_name: nodejs-rs-db  
    healthcheck:
      test: "exit 0" 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_PUBLISHED_PORT: ${DB_PUBLISHED_PORT}
    networks:
      - my-network
    ports:
      - published: 5432
        target: 5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-rs-server
    environment:
      PORT: ${PORT}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
    volumes:
      - ./:/app
    networks:
      - my-network
    ports:
      - "4000:4000"
    restart: unless-stopped

volumes:
  postgres-db:   

version: '3.9'




