networks:
  default:
    name: rs-nodejs-network

services:
  db:
    build:
      context: ./dockerfiles/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - default
    ports:
      - published: 8002
        target: 5432
    restart: always

  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
    volumes:
      - ./:/usr/src/app
    command: npm run start
    networks:
      - default
    ports:
      - 4000:4000
    restart: always

version: '3.9'




