networks:
  my-network:
    name: rs-nodejs-network

services:
  db:
    build:
      context: ./dockerfiles/db
      dockerfile: Dockerfile
    container_name: nodejs-rs-db   
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - my-network
    ports:
      - published: 8002
        target: 5432
    restart: always

  server:
    depends_on:
      db:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-rs-server  
    environment:
      PORT: ${PORT}
    volumes:
      - ./:/app
    networks:
      - my-network
    ports:
      - "4000:4000"
    restart: always

version: '3.9'




